# Generated by Django 2.0.6 on 2018-06-14 14:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='temperatureRecorde',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='uuid')),
                ('temperature', models.IntegerField(default=0, null=True, verbose_name='当前温度')),
                ('createTime', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='数据创建时间')),
            ],
            options={
                'db_table': 'temperature_recorde',
                'ordering': ['-createTime'],
            },
        ),
    ]
